[package]
name = "m5oooo"
version = "0.1.0"
authors = ["kenkoooo <kenkou.n@gmail.com>"]
edition = "2018"

[dependencies]
xtensa-lx-rt = { version="0.5.0", features=["lx6"] }
xtensa-lx = { version="0.3.0", features=["lx6"] }
panic-halt = "0.2.0"
esp32-hal = "0.2.0"